=== wuhuqifei1/xiangmu/Document/product.dtd
<?xml version="1.0" encoding="UTF-8"?>
	<!ELEMENT products (product+)>
	<!ELEMENT product (name,price,color,xx,kc)>
	<!ATTLIST product ID CDATA #REQUIRED>
	<!ELEMENT name (#PCDATA)>
  	<!ELEMENT price (#PCDATA)>
   	<!ELEMENT color (#PCDATA)>
   	<!ELEMENT xx (#PCDATA)>
   	<!ELEMENT kc (#PCDATA)>

=== wuhuqifei1/xiangmu/Document/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE students SYSTEM 'product.dtd'>
<products>
	<product ID="P001">
		<name>蜘蛛王皮鞋</name>
		<price>268</price>
		<color>黑色</color>
		<xx>42</xx>
		<kc>500</kc>
	</product>
	<product ID="P002">
		<name>ThinkPad x240</name>
		<price>5678</price>
		<color>黑色</color>
		<xx>12</xx>
		<kc>50</kc>
	</product>
	<product ID="P003">
		<name>WD移动硬盘</name>
		<price>568</price>
		<color>蓝色</color>
		<xx>5</xx>
		<kc>1000</kc>
	</product>
</products>
